### ISSUE TITLE
You have a new variant.

### ISSUE THREAD

**Issue by rdebath** [ioncodes/brainfuck-c#1]
Thanks, you've added a new entry to my "how to program brainfuck interpreters incorrectly" collection.

BTW: If you're interested in fixing your interpreter the below program should print `OK` and a newline.

``` bf
++++++++++[>++++++++>+<<-]>-.<----[>-<+][[]>++<][+]>.>.
```

**Comment by ioncodes** [comment]
Yeah, it prints OK and a newline. So where's the problem?
![img](https://i.imgur.com/wQHlkt6.png)

**Comment by rdebath** [comment]
No problem now; you fixed it. I caught one of your earlier versions.

**Comment by ioncodes** [comment]
Alright, no problems :) Feel free to make new issues if you find any :)
